@startuml viewArticle
actor Reader
participant "League Alert System" as LAS

Reader -> LAS : Request Articles by tag
activate LAS

alt Success
    LAS -> Reader : Return Articles

deactivate LAS



deactivate LAS
@enduml
