@startuml

title Reset Password - Design Level Sequence Diagram

actor User 

participant ReactApplication as "<<View>>\nReactApplication"
participant ResetPasswordPage as "<<View>>\nResetPasswordPage"
participant AuthController as "<<Controller>>\nAuthController"
participant AuthServiceImpl as "<<Service>>\nAuthServiceImpl"
participant Auth0Client as "<<External Service>>\nAuth0Client"

User -> ReactApplication : Access "Reset Password Page"
activate ReactApplication

ReactApplication -> ResetPasswordPage : render()

User -> ResetPasswordPage : Enter email and submit request

ResetPasswordPage -> AuthController : POST /resetPassword(email)
activate AuthController

AuthController -> AuthServiceImpl : resetPassword(email)
activate AuthServiceImpl

AuthServiceImpl -> Auth0Client : sendResetPasswordEmail(email)
activate Auth0Client

Auth0Client -> AuthServiceImpl : Return success message\n"Reset Email Sent"
deactivate Auth0Client

AuthServiceImpl -> AuthController : Return success message
deactivate AuthServiceImpl

AuthController -> ReactApplication : Return success message\n"Reset Password Email Sent!"
deactivate AuthController

ReactApplication -> ResetPasswordPage : Display confirmation message\n"Check your email for reset link."
ResetPasswordPage -> User : Show confirmation message

deactivate ReactApplication

@enduml
