name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_124126177 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: Create coverage-data directory and copy contents
        id: zipreports
        if: success() || failure()
        run: |
          mkdir -p .qodana/code-coverage
          for service in $(find -maxdepth 1 -type d -name '*service*' -o -name '*gateway*' | sed 's/.\///'); do
            if [[ -d "$service/build" && -d "$service/build/reports" ]]; then
              cp -R "$service/build/reports" ".qodana/code-coverage/$service"
            fi
          done
      - name: Archive coverage data
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data
          path: .qodana/code-coverage

      - name: Jacoco PR Comment
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90
          min-coverage-changed-files: 90
          title: Jacoco Coverage Report
          update-comment: true
          continue-on-error: true
