@startuml
actor Admin
participant "League Alerts System" as LAS

ref over Admin, LAS : Create Author Account

opt Modify Admin Account
    Admin -> LAS: createAuthorAccount(authorRequestDTO)
    activate LAS
        LAS -> LAS: Save Updated Data
        LAS -> LAS: assignAuthorRole(userId)
        LAS --> Admin: returnSuccessMessage(HttpStatusCode.OK)
    deactivate LAS
end opt
@enduml